[versions]
agp = "8.2.2"
androidTools = "31.13.0"
composeBom = "2025.09.00"
composeCompiler = "1.5.7"
mockkVersion = "1.14.5"
kotlin_version = "2.0.0"
ksp_version = "2.0.0-1.0.23"
ktorVersion = "3.3.0"
timber = "5.0.1"
jetbrainsKotlinJvm = "2.0.0"

[libraries]
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorVersion"}
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktorVersion"}
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktorVersion"}
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktorVersion"}
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktorVersion"}
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockkVersion"}
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockkVersion"}

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp"}
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools"}
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin_version"}
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version"}
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version"}
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }