[versions]
agp = "8.13.0"
androidJunitVersion = "1.3.0"
androidTools = "31.13.0"
appcompat = "1.7.1"
archCoreVersion = "2.2.0"
composeActicityVerions = "1.9.0"
composeBom = "2025.09.01"
composeCompiler = "1.5.7"
coreKtx = "1.17.0"
coroutinesAndroidVersion = "1.10.2"
datastorePreferences = "1.1.7"
espressoCore = "3.7.0"
hamcrestVersion = "1.3"
junitVersion = "4.13.2"
kotlin_version = "2.2.20"
ksp_version = "2.2.20-2.0.3"
ktorVersion = "3.3.2"
logbackVersion = "1.5.18"
material = "1.13.0"
mockkVersion = "1.14.5"
robolectricVersion = "4.16"
roomVersion = "2.8.1"
slf4jAndroidVersion = "1.7.36"
timber = "5.0.1"
materialVersion = "1.13.0"

[libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp"}
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-arch-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreVersion"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJunitVersion"}
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActicityVerions"}
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
compose-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4"}
compose-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
compose-material = { group = "androidx.compose.material3", name = "material3"}
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended"}
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
compose-ui = { group = "androidx.compose.ui", name = "ui"}
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesAndroidVersion"}
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutinesAndroidVersion"}
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesAndroidVersion"}
hamcrest = { group = "org.hamcrest", name = "hamcrest-all", version.ref = "hamcrestVersion"}
junit = { group = "junit", name = "junit", version.ref = "junitVersion"}
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin_version"}
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version"}
ktor-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktorVersion"}
ktor-client = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorVersion"}
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktorVersion"}
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktorVersion"}
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktorVersion"}
#ktor-logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion"}
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktorVersion"}
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktorVersion"}
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktorVersion"}
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockkVersion"}
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockkVersion"}
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectricVersion"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion"}
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion"}
slf4j-android = { group = "org.slf4j", name = "slf4j-android", version.ref = "slf4jAndroidVersion" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber"}
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

[bundles]
androidTestLibs = ["androidx-junit", "androidx-arch-testing", "coroutines-test", "androidx-espresso-core", "mockk-android"]
composeToolingLib = ["compose-manifest", "compose-tooling"]
composeLibs = ["compose-bom", "compose-graphics", "compose-material", "compose-material-icons", "compose-preview"]
ktorLibs = ["ktor-auth", "ktor-client", "ktor-client-cio", "ktor-client-mock", "ktor-content-negotiation", "ktor-logging", "ktor-okhttp", "ktor-serialization", "slf4j-android"]
testLibs = ["coroutines-test", "junit", "hamcrest", "robolectric", "mockk-android", "mockk-agent"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin_version" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin_version"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }

# Plugins defined by this project
com-martdev-android-application = { id = "com.martdev.android.application", version = "unspecified"}
com-martdev-android-compose-library = { id = "com.martdev.android.compose.library", version = "unspecified" }
com-martdev-android-library = { id = "com.martdev.android.library", version = "unspecified"}
com-martdev-android-feature = { id = "com.martdev.android.feature", version = "unspecified"}
android-library = { id = "com.android.library", version.ref = "agp" }