[versions]
agp = "8.2.2"
androidTools = "31.5.2"
kotlin_version = "2.0.0"
ksp_version = "2.0.0-1.0.23"

[libraries]

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp"}
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools"}
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin_version"}
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp_version"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }