[versions]
agp = "8.2.2"
kotlin_version = "2.0.0"
ksp_version = "2.0.0-1.0.23"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }