name: MiGaleria Build

on:
  pull_request:
    branches: [ "master", "developer" ]
  push:
    branches: [ "master", "developer" ]

permissions:
  contents: read

jobs:
  build_and_test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4
        if: always() # Upload reports even if tests fail
        with:
          name: unit-test-reports
          path: |
            core/domain/build/reports/tests/testDebugUnitTest
            core/remote/build/reports/tests/testDebugUnitTest

  androidTest:
    needs: build_and_test
    runs-on: ubuntu-latest
    timeout-minutes: 55
    strategy:
      matrix:
        api-level: [26]

    steps:
      - name: Delete unnecessary tools
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: false
          tool-cache: true
          dotnet: true
          haskell: true
          swap-storage: true
          large-packages: false

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Enable KVM for hardware acceleration
        run:  |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up prerequisites
        run: sudo apt-get update && sudo apt-get install -y libx11-6 libgl1 libpulse0 libgl1-mesa-glx

      - name: Start adb server
        run: $ANDROID_HOME/platform-tools/adb start-server

      - name: Clean emulator state
        run: rm -rf ~/.android/emu-update-last-check.ini ~/.android/*snapshot*

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDemoDebugAndroidTest --daemon

      - name: Upload Instrumented Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: instrumented-test-reports-api-${{ matrix.api-level }}
          path: |
            **/build/reports/androidTests/connected/
            **/build/outputs/androidTest-results/connected/

  build_release_apk:
    name: Build Release APK
    needs: build_and_test

    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Decode Keystore File
        run: echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > app/mg_keystore.jks

      - name: Assemble Release APK with Secrets
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        # The command to build a release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
